### ISSUE TITLE
Does not work on latest GNOME update

### ISSUE THREAD

**Issue by omkensey** [sunwxg/gnome-shell-extension-unlockDialogBackground#11]
GNOME fixed a bug in the blur code, and [the fix seems to have affected extensions that interact with blurring or locking](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2981).

**Comment by sunwxg** [comment]
Thank you for the finding.

**Comment by omkensey** [comment]
Confirmed the update works again!  Thanks!
