### ISSUE TITLE
extensions.gnome.org installs version 14 instead of 15 on 3.36.5

### ISSUE THREAD

**Issue by LoneFenris** [sunwxg/gnome-shell-extension-unlockDialogBackground#13]
It appears that at least on 3.36.5, when installing from extensions.gnome.org, it tries to install version 14 for 3.36 instead of the most recent version 15 for 3.36.4.

Upon manually installing version 15, it informs of an update available that will then downgrade back to version 14.

**Comment by LoneFenris** [comment]
Okay, I can't seem to reproduce the downgrade attempt after a manual install. It still installs the wrong version from e.g.o for some reason, though. Changing the issue title.

**Comment by sunwxg** [comment]
Updated the meta data.
Thank you.
