### ISSUE TITLE
install issues with PopOs 20.04, issue hbox.append not a function

### ISSUE THREAD

**Issue by squalou** [sunwxg/gnome-shell-extension-unlockDialogBackground#17]
Hi,
I'm experimenting with PopOS, and I don't know why but I cannot use extensions.gnome.org site to install extensions.

So, and did a git clone / make install

At HEAD, when going to exensios / clicking 'configure' cog, I get the error

```js
hbox.append is not a function
```

So, I did checkout a previous commit, and it works fine. I did use e45c8de5962a1f47071b580284c8836a39bf0081 : 'Update to 3.38', so obviously before 'Adapt to 40'.

What I'm missing here is not much : on gnome extensions website there's supposed to be a dropdown menu to choose the correct Gnome Shell version.
Using this git repo, I don"t know how to do thid. Did I miss something ?  I as expecting a tag or something.

I'd be glad if you had any idea as how to get the right commit for the right gnome shell version :)

Thank you for your work anyway (can't believe Gnome folks don't include these configuration options) !

**Comment by sunwxg** [comment]
I think your way is right. I don't tag the repo, so you can't find the tag.
If you want to get it from extensions.gnome.org, you can download the zip file on the web page after you select the right gnome-shell version, then unzip the file and copy it to `~/.local/share/gnome-shell/extensions/`.

**Comment by squalou** [comment]
cool ! thank you, I'll do that.
