### ISSUE TITLE
Gnome 42: GSettings key picture-uri-dark not found in schema org.gnome.shell.extensions.unlockDialogBackground

### ISSUE THREAD

**Issue by freddyw** [sunwxg/gnome-shell-extension-unlockDialogBackground#22]
When using this extension on Fedora 42 with the 'Appearance' preference set to dark this error is thrown:

gnome-shell[1595]: JS ERROR: Error: GSettings key picture-uri-dark not found in schema org.gnome.shell.extensions.unlockDialogBackground

That key is indeed missing in the settings. The picture-dark is new afaik, likewise in the background section of gnome42. There are now 2 distinct values:
org.gnome.desktop.background. picture-uri 
org.gnome.desktop.background.picture-uri-dark

**Comment by sunwxg** [comment]
Thank you!
Fixed by commit https://github.com/sunwxg/gnome-shell-extension-unlockDialogBackground/commit/0c6723b0c2f05fec35884c191e985d774e4bd02c
