### ISSUE TITLE
Lock screen is changed only for the first lock after toggling the extension

### ISSUE THREAD

**Issue by AntonAkovP** [sunwxg/gnome-shell-extension-unlockDialogBackground#24]
Hey, I've been having this issue after updating from Fedora 34 to 36. If I toggle the extension on and off the first time I lock it will work perfect, however after I unlock and lock again I get the default background. Other than using my password, I also usually unlock using `loginctl unlock-session` through KDE connect but the issue persists either way. 
Gnome version 42.4, using X11
If I can help you with any logs or anything let me know, thanks!

**Comment by sunwxg** [comment]
> If I toggle the extension on and off the first time I lock it will work perfect,

Sorry, I can't understand here. Is the extension enabled or not?

**Comment by AntonAkovP** [comment]
my bad, should've said off and on.
It is on, and works properly the first lock. Then without touching it I keep getting the default background.

**Comment by sunwxg** [comment]
Did you update the extension after you upgraded the system from Fedora 34 to 36?

**Comment by AntonAkovP** [comment]
I think I had to reinstall it completely with a bunch of other ones.
Extension version is 27

**Comment by sunwxg** [comment]
The extension version is right.
I guess the extension becomes disabled after you unlock the screen, so you keep getting the default background.
Maybe some other extension has fault to make all extensions disable.

**Comment by AntonAkovP** [comment]
You are right, I discovered the [Blur my Shell](https://extensions.gnome.org/extension/3193/blur-my-shell/) extension is breaking it, no matter the lock screen blur option.
I'm closing this issue and I may take it up with them. Thank you for the prompt replies!
