### ISSUE TITLE
Works only first time and then not work untill toggling Extension

### ISSUE THREAD

**Issue by afzl-wtu** [sunwxg/gnome-shell-extension-unlockDialogBackground#25]
I am using Fedora 38 with gnome 44.2.
How to reproduce error:
1. Choose your wallpaper XYZ 
2. Enable the extension.
3.Now press Windows(or Super key)+L. Which will display lock screen with choosen wallpaper XYZ.
Now unlock screen by inputting  password and lock again.. This time wallpaper XYZ is not shown instead default blurred wallpaper is shown.
Now to work again you need to disable and enable extension again.

**Comment by sunwxg** [comment]
I can't reproduce it on my gnome 44.2. Dose it conflict with other extensions?

**Comment by afzl-wtu** [comment]
Thanks for reply. I found the problem. The extension is conflicting with "Blur My Shell" extenion.
