### ISSUE TITLE
Background changed on lock screen but the password screen on login screen has a solid color

### ISSUE THREAD

**Issue by blueray453** [sunwxg/gnome-shell-extension-unlockDialogBackground#26]
Background changed on lock screen but the password screen on login screen has a solid color

![file](https://github.com/sunwxg/gnome-shell-extension-unlockDialogBackground/assets/855297/420522b2-2aea-45ba-8f58-64c32168898c)

I mean when I press `super+l`, it shows the background, but when i press `space` to enter password, there is no background image, only a solid color.

**P.S.** This is a random image from the internet to give an example.

**Comment by sunwxg** [comment]
When inputting password, the background is blur picture of desktop background. What is your desktop background?

**Comment by blueray453** [comment]
Here I am attaching my background. It is a .png image.

![firefox_wallpaper](https://github.com/sunwxg/gnome-shell-extension-unlockDialogBackground/assets/855297/b6d3b3ea-186d-4f40-8f5f-22a60b2f418b)

**Comment by sunwxg** [comment]
This image is almost one color, after blurred it will be like a solid color.

**Comment by blueray453** [comment]
In that case it is ok. Thank you very much.
