### ISSUE TITLE
Settings error

### ISSUE THREAD

**Issue by kamilizmer** [sunwxg/gnome-shell-extension-unlockDialogBackground#3]
After trying to open settings I have this:

<img src="https://i.imgur.com/GcZrl17.png" />

**Comment by sunwxg** [comment]
Oh, which distribution do you use?
My OS is openSUSE, on openSUSE you need install the typelib-1_0-Clutter-1_0 package. And It is default installed when install GNOME environment.

**Comment by kamilizmer** [comment]
> Oh, which distribution do you use?
> My OS is openSUSE, on openSUSE you need install the typelib-1_0-Clutter-1_0 package. And It is default installed when install GNOME environment.

I have Ubuntu 18.10 with Gnome 3.30 and I don't have that lib like default. Thanks! I installed that and work perfectly ;)

**Comment by kamilizmer** [comment]
Fixed
