### ISSUE TITLE
multi monitor setup

### ISSUE THREAD

**Issue by Zeka13** [sunwxg/gnome-shell-extension-unlockDialogBackground#9]
Hello, thanks for a great extension.

When it was a part of vanila gnome, I use to 
`gsettings set org.gnome.desktop.screensaver picture-options "wallpaper"`

for multiscreen support

Is it possible with your solution? If yes, how? 

Thx in advice

**Comment by sunwxg** [comment]
```
gsettings --schemadir .local/share/gnome-shell/extensions/unlockDialogBackground@sun.wxg@gmail.com/schemas/ set org.gnome.shell.extensions.unlockDialogBackground picture-options 'wallpaper'
```

**Comment by Zeka13** [comment]
@sunwxg thx!
